### ISSUE TITLE
Listener modules requires its own library.

### ISSUE THREAD

**Issue by drq** [eclipse-volttron/docker#8]
**Describe the bug**
Listener modules requires its own library in the config yaml file such as

```
# Agents dictionary to install. The key must be a valid identity for the agent to be installed correctly.
agents:
  listener:
    source: volttron-listener
    tag: listener
    libraries:
      - volttron-listener
```
